### ISSUE TITLE
feat(manifest): gate actions in manifest.json via _featureFlag with feature-flags.local.json override

### ISSUE THREAD

**Issue by niklam** [niklam/iracedeck#363]
## Summary

Extend the platform feature flag system (introduced in #258) so individual actions in `manifest.json` can be gated by a feature flag. Lets us commit a beta/in-development action but keep it hidden from everyone by default, visible only to testers who flip the flag on via `feature-flags.local.json`.

**In scope:** per-action gating in the manifest via an `_featureFlag` field, with build-time filtering. **Not in scope:** deduplicating the two per-plugin manifests into a shared source (that's a separate, bigger effort; file separately if desired).

### Move `manifest.json` to build-output status

Today `packages/iracing-plugin-<platform>/com.iracedeck.sd.core.sdPlugin/manifest.json` is committed. To filter actions at build time, the committed file and the file the host app reads must be separate:

- **Committed source**: `packages/iracing-plugin-<platform>/manifest.json` (moved up one directory, out of the sdPlugin folder). Contains the full list of actions, with optional `_featureFlag` annotations.
- **Build output**: Rollup writes the filtered, stripped manifest to `packages/iracing-plugin-<platform>/com.iracedeck.sd.core.sdPlugin/manifest.json`.
- **Gitignore**: add `*.sdPlugin/manifest.json` to each plugin's `.gitignore`, matching the existing pattern for `bin/` and `ui/`.

### Annotation format

In the source manifest, an action can opt into gating by adding a single field:

```json
{
  "Name": "Beta Camera Mode",
  "UUID": "com.iracedeck.sd.core.beta-camera",
  "_featureFlag": "betaCameraMode",
  "Icon": "imgs/actions/beta-camera/icon",
  ...
}
```

### Build-time filter

In each plugin's `rollup.config.mjs`, add a step that runs during `generateBundle`:

1. Read the source `manifest.json` (at the package root).
2. For each entry in `Actions`:
   - If it has `_featureFlag` set and the merged `platformFeatures.features[<flagName>]` is `false`, drop the entry.
   - Otherwise, strip the `_featureFlag` field and keep the entry.
3. Write the filtered manifest to `com.iracedeck.sd.core.sdPlugin/manifest.json`.

The flag is resolved against the same merged `platformFeatures` object we already build (committed `platform-features.json` deep-merged with optional root `feature-flags.local.json`).

### Declaring the flag

For each new gate-worthy action, add its flag name to:

- Both `packages/iracing-plugin-<platform>/platform-features.json` (under `features`, typically `false` by default for committed betas).
- The `PlatformFeatureFlags` interface in `packages/deck-core/src/plugin-config.ts`.
- The `__FEATURE_*__` ambient declaration in `packages/icon-composer/src/platform-features.d.ts` (if the action code also needs the compile-time constant — optional).

### Override surface (for testers)

Same as the existing system: create `feature-flags.local.json` at repo root (gitignored):

```json
{ "features": { "betaCameraMode": true } }
```

Rebuild to pick it up. No other changes; the file overlays both plugins' manifests.

### Plugin.ts considerations

Unrelated — gating only affects `manifest.json`. Actions are still imported and registered in `plugin.ts`; the Stream Deck / Mirabox host simply won't see them because they're not in the manifest. If dead-code elimination of unused action code is desired, that can be addressed later by also gating the `adapter.registerAction(...)` call with `__FEATURE_*__`.

## First use case

Any beta or limited-rollout action. No specific action lined up yet — the issue is primarily enabling the infrastructure.

## Files to create / modify

| File | Status | Purpose |
|------|--------|---------|
| `packages/iracing-plugin-stream-deck/manifest.json` | new (moved from sdPlugin folder) | Source manifest with optional `_featureFlag` fields |
| `packages/iracing-plugin-mirabox/manifest.json` | new (moved from sdPlugin folder) | Same for Mirabox |
| `packages/iracing-plugin-stream-deck/com.iracedeck.sd.core.sdPlugin/manifest.json` | remove from git | Becomes build output |
| `packages/iracing-plugin-mirabox/com.iracedeck.sd.core.sdPlugin/manifest.json` | remove from git | Becomes build output |
| `packages/iracing-plugin-stream-deck/.gitignore` | modify | Add `*.sdPlugin/manifest.json` |
| `packages/iracing-plugin-mirabox/.gitignore` | modify | Add `*.sdPlugin/manifest.json` |
| `packages/iracing-plugin-stream-deck/rollup.config.mjs` | modify | Add `emit-manifest` plugin that filters + writes manifest |
| `packages/iracing-plugin-mirabox/rollup.config.mjs` | modify | Same |
| `.claude/rules/platform-feature-flags.md` | modify | Document the `_featureFlag` manifest pattern |
| `.claude/CLAUDE.md` (and plugin CLAUDE.mds) | modify | Note the new manifest source location when documenting "how to add an action" |

## Verification

- [ ] Source `packages/iracing-plugin-<platform>/manifest.json` (with an `_featureFlag` entry set to a false-by-default flag) produces a built `com.iracedeck.sd.core.sdPlugin/manifest.json` **without** that action.
- [ ] Same source with `feature-flags.local.json` overriding the flag to true produces a built manifest **with** that action, and no `_featureFlag` field leaks into the output.
- [ ] Actions without `_featureFlag` are unaffected — they appear in the output manifest unchanged.
- [ ] Both plugins build cleanly; existing tests still pass.
- [ ] Stream Deck and Mirabox host apps load the generated manifest without complaints.

**Comment by niklam** [comment]
Closing as not needed yet: this is enabling infrastructure with no concrete beta action lined up since filing (April 2026). The flag plumbing it builds on (platform-features.json + feature-flags.local.json deep-merge) is intact, so the approach remains viable — reopen or re-file when a real beta/limited-rollout action exists. Note for a future revival: the Ulanzi plugin now exists (third manifest, differently named sdPlugin folder), the shared icon-composer platform-features.d.ts was retired in #642 (per-plugin declarations now), and a manifest-gating flag can be runtime-only like the profiles flag — no __FEATURE_*__ constant needed.
